# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/EN525.742_radio/vivado/radio_periph_lab.srcs/sources_1/bd/design_1/ip/design_1_ps7_0_axi_periph_imp_auto_cc_0/design_1_ps7_0_axi_periph_imp_auto_cc_0.xci
# IP: The module: 'design_1_ps7_0_axi_periph_imp_auto_cc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/EN525.742_radio/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_ps7_0_axi_periph_imp_auto_cc_0/design_1_ps7_0_axi_periph_imp_auto_cc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ps7_0_axi_periph_imp_auto_cc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/EN525.742_radio/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_ps7_0_axi_periph_imp_auto_cc_0/design_1_ps7_0_axi_periph_imp_auto_cc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ps7_0_axi_periph_imp_auto_cc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/EN525.742_radio/vivado/radio_periph_lab.srcs/sources_1/bd/design_1/ip/design_1_ps7_0_axi_periph_imp_auto_cc_0/design_1_ps7_0_axi_periph_imp_auto_cc_0.xci
# IP: The module: 'design_1_ps7_0_axi_periph_imp_auto_cc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/EN525.742_radio/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_ps7_0_axi_periph_imp_auto_cc_0/design_1_ps7_0_axi_periph_imp_auto_cc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ps7_0_axi_periph_imp_auto_cc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/EN525.742_radio/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_ps7_0_axi_periph_imp_auto_cc_0/design_1_ps7_0_axi_periph_imp_auto_cc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ps7_0_axi_periph_imp_auto_cc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
