# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/EN525.742_radio/ip_repo/full_radio/src/dds_compiler_1/dds_compiler_1.xci
# IP: The module: 'dds_compiler_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/EN525.742_radio/lab5.gen/sources_1/ip/dds_compiler_1/dds_compiler_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_compiler_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/EN525.742_radio/ip_repo/full_radio/src/dds_compiler_1/dds_compiler_1.xci
# IP: The module: 'dds_compiler_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/EN525.742_radio/lab5.gen/sources_1/ip/dds_compiler_1/dds_compiler_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_compiler_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
